[package]
name = "hashchain"
version = "0.0.1"
repository = "https://github.com/DLTcollab/hashchain"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
openssl = "0.10"
blake3 = "0.3.3"
